### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by svillagracia** [AraLawrence/tripper#49]
Hey, team. Was exploring about your application and found this. Thought you might want to look at it with your event coming up and all. Cheers!

![image](https://cloud.githubusercontent.com/assets/10122668/12427277/2b01126a-be93-11e5-96e9-d05a008a3ccc.png)

**Comment by AraLawrence** [comment]
Thanks for the head's up! Changed the referrers, the maps do render now.
